const Permissions = {
  // USERS
  CREATE_USERS: 'CREATE_USERS',
  READ_USERS: 'READ_USERS',
  EDIT_USERS: 'EDIT_USERS',
  DELETE_USERS: 'DELETE_USERS',
  // CLASSES
  CREATE_CLASSES: 'CREATE_CLASSES',
  READ_CLASSES: 'READ_CLASSES',
  EDIT_CLASSES: 'EDIT_CLASSES',
  DELETE_CLASSES: 'DELETE_CLASSES',
  // PROFILES
  CREATE_PROFILES: 'CREATE_PROFILES',
  READ_PROFILES: 'READ_PROFILES',
  EDIT_PROFILES: 'EDIT_PROFILES',
  DELETE_PROFILES: 'DELETE_PROFILES',
  // CATEGORIES
  CREATE_CATEGORIES: 'CREATE_CATEGORIES',
  READ_CATEGORIES: 'READ_CATEGORIES',
  EDIT_CATEGORIES: 'EDIT_CATEGORIES',
  DELETE_CATEGORIES: 'DELETE_CATEGORIES',
}

module.exports = Permissions
